<?xml version="1.0" encoding="utf-8"?><Database Name="Estoque" Class="EstoqueDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Estoque.mdf;Integrated Security=True" SettingsObjectName="Linq_ToSQL.My.MySettings" SettingsPropertyName="EstoqueConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Produtos" Member="Produtos">
    <Type Name="Produto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="preco" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>